name: "Validate"

on:
  workflow_dispatch:
  schedule:
    - cron:  "0 0 * * *"
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  validate-hacs:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - name: HACS validation
        uses: "hacs/action@main"
        with:
            category: "integration"
            # Remove this 'ignore' key when you have added brand images for your integration to https://github.com/home-assistant/brands
            ignore: "brands"